name: Auto Merge Master Into Develop

# Credit this solution to: https://stackoverflow.com/questions/35445186/can-github-automatically-merge-branches
# Ensure permissions are correct: https://stackoverflow.com/questions/72851548/permission-denied-to-github-actionsbot

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

concurrency: 
  group: auto-merge
  cancel-in-progress: true

env:
  MY_REPO: https://segunak:${{secrets.GITHUB_TOKEN}}@github.com/segunak/third-places-data.git
  MY_BRANCH: develop
  MASTER_REPO: https://github.com/segunak/third-places-data.git
  MASTER_BRANCH: master

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Merge master into develop
      run: |
        git clone ${{env.MY_REPO}} -b ${{env.MY_BRANCH}} tmp
        cd tmp
        git config user.name "Auto Merge Bot"
        git config user.email "bot@automerge.com"
        git config pull.rebase false
        git pull ${{env.MASTER_REPO}} ${{env.MASTER_BRANCH}}
        git push